version: 2.1

orbs:
  maven: circleci/maven@dev:<<pipeline.git.revision>>
  orb-tools: circleci/orb-tools@11.1

filters: &filters
  tags:
    only: /.*/

jobs:
  integration-test-1:
    executor: maven/default
    steps:
      - checkout
      - run:
          name: Check if Maven is installed
          command: |-
            if [[ $(command -v mvn) == "" ]]; then
              echo " Maven is not installed "; exit 1;
            else
              echo Maven successfully installed.
            fi
      - maven/test: 
          app_src_directory: sample_app

workflows:
  test-deploy:
    jobs:
      - orb-tools/pack:
          filters: *filters
      - integration-test-1:
          filters: *filters
      - orb-tools/publish:
          orb-name: circleci/maven
          vcs-type: << pipeline.project.type >>
          pub-type: production
          requires:
            - orb-tools/pack
            - integration-test-1
          context: orb-publisher
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v[0-9]+\.[0-9]+\.[0-9]+$/
