version: 2.1

orbs:
  maven: circleci/maven@dev:<<pipeline.git.revision>>
  orb-tools: circleci/orb-tools@11.1

filters: &filters
  tags:
    only: /.*/

workflows:
  test-deploy:
    jobs:
      - orb-tools/pack:
          filters: *filters
      - maven/test: 
          app_src_directory: sample_app
          command: test -DforkCount=4
          filters: *filters
      - maven/parallel_test:
          command: "verify"
          parallelism: 4
          test_results_path: sample_app2/target/surefire-reports
          test_directory: "."
      - orb-tools/publish:
          orb-name: circleci/maven
          vcs-type: << pipeline.project.type >>
          pub-type: production
          requires:
            - orb-tools/pack
            - maven/test
            - maven/parallel_test
          context: orb-publisher
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v[0-9]+\.[0-9]+\.[0-9]+$/
