version: 2.1

orbs:
  # The orb we're building will be injected using the 'orb-under-test' name.
  # (because config.yml's continue stage said "orb-name: orb-under-test")
  orb-tools: circleci/orb-tools@12

filters: &filters
  tags:
    only: /.*/

workflows:
  test-deploy:
    jobs:
      - orb-under-test/test:
          filters: *filters
          name: test
          app_src_directory: sample_app
          command: test -DforkCount=4
      - orb-tools/pack:
          filters: *filters
          requires:
            - test
      - orb-tools/publish:
          orb_name: circleci/maven
          vcs_type: << pipeline.project.type >>
          pub_type: production
          requires:
            - orb-tools/pack
          context: orb-publisher
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v[0-9]+\.[0-9]+\.[0-9]+$/
