# How to author Executors: https://circleci.com/docs/2.0/reusing-config/#authoring-reusable-executors
description: |
  The latest minor and patch update of the version 13 JDK image provided by CircleCI.
docker:
  - image: "cimg/openjdk:<<parameters.tag>>"
parameters:
  tag:
    default: "13.0"
    description: |
      Can be changed to any of the available tags listed on the DockerHub for this image.
      https://hub.docker.com/r/cimg/openjdk/tags
    type: string
